# Generated by Django 2.0 on 2017-12-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_auto_20171225_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
