# Generated by Django 2.0 on 2017-12-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voteapp.Votings')),
            ],
        ),
    ]
