# Generated by Django 2.0 on 2017-12-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='voteapp.Users'),
        ),
    ]
