# Generated by Django 2.0 on 2017-12-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0006_auto_20171225_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
