# Generated by Django 2.0 on 2018-01-14 15:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('voteapp', '0008_auto_20180113_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variants',
            new_name='Options',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='voting_id',
            new_name='voting',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='variant_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='user_id',
            new_name='user',
        ),
    ]
