# Generated by Django 2.0 on 2018-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0008_auto_20180113_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
