# Generated by Django 2.0 on 2018-01-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0009_auto_20180114_1028'),
        ('voteapp', '0009_auto_20180114_1516'),
    ]

    operations = [
    ]
