# Generated by Django 2.0 on 2018-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0013_auto_20180122_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='polls',
            field=models.ManyToManyField(related_name='tag', to='voteapp.Poll'),
        ),
    ]
