# Generated by Django 2.0 on 2018-09-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0015_comment_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_checkbox',
        ),
        migrations.AddField(
            model_name='poll',
            name='photo',
            field=models.ImageField(default='voteapp/media/userphoto/default.png', upload_to='user_photo'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
