# Generated by Django 2.0 on 2018-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0016_auto_20180929_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='photo',
            field=models.ImageField(default='userphoto/default.png', upload_to='userphoto'),
        ),
    ]
