# Generated by Django 2.0 on 2018-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0017_auto_20180929_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
