# Generated by Django 2.0 on 2018-09-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0018_auto_20180929_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='photo',
        ),
    ]
