# Generated by Django 2.0 on 2018-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0019_remove_poll_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
